# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# rcpp population interface ----
## Setup ----
# Load or prepare any necessary data for testing

## IO correctness ----
test_that("rcpp population interface works with correct inputs", {
  # setup population to create test values
  population <- methods::new(Population)
  n_years <- 10
  n_ages <- 10
  log_M_length <- n_years * n_ages
  population$log_M[] <- rep(-1, log_M_length)

  population$log_init_naa[] <- rep(0, n_ages)

  population$log_init_naa$set_estimation_types(c("fixed_effects"))
  population$n_ages$set(n_ages)
  population$ages[] <- seq(1, n_ages)
  population$n_fleets$set(2)
  population$n_years$set(n_years)


  #' @description Test that the population id is 1.
  expect_equal(
    object = population$get_id(),
    expected = 1
  )

  for (i in 1:(n_years * n_ages)) {
    #' @description Test that the log_M values are all -1.
    expect_equal(
      object = population$log_M[i]$value,
      expected = -1
    )
    #' @description Test that the log_M values are not estimated.
    expect_equal(
      object = population$log_M[i]$estimation_type$get(), "constant"
    )
  }

  for (i in 1:n_years) {
    #' @description Test that the log_init_naa values are all 0.
    expect_equal(
      object = population$log_init_naa[i]$value,
      expected = 0
    )
    #' @description Test that the log_init_naa values are estimated.
    expect_equal(
      object = population$log_init_naa[i]$estimation_type$get(), "fixed_effects"
    )
  }

  population$log_init_naa$set_estimation_types(c("constant"))
  population$log_M$set_estimation_types(c("fixed_effects"))

  for (i in 1:(n_years * n_ages)) {
    #' @description Test that the log_M values are all -1.
    expect_equal(
      object = population$log_M[i]$value,
      expected = -1
    )
    #' @description Test that the log_M values are now estimated.
    expect_equal(
      object = population$log_M[i]$estimation_type$get(), "fixed_effects"
    )
  }

  for (i in 1:n_years) {
    #' @description Test that the log_init_naa values are all 0.
    expect_equal(
      object = population$log_init_naa[i]$value,
      expected = 0
    )
    #' @description Test that the log_init_naa values not estimated.
    expect_equal(
      object = population$log_init_naa[i]$estimation_type$get(), "constant"
    )
  }

  clear()
})

test_that("sex_structure defaults and round-trips through Set/GetSexStructure", {
  population <- methods::new(Population)

  #' @description Test that sex_structure defaults to sex_ratio_at_age.
  expect_equal(
    object = population$GetSexStructure(),
    expected = "sex_ratio_at_age"
  )

  population$SetSexStructure("explicit_two_sex")

  #' @description Test that SetSexStructure updates GetSexStructure.
  expect_equal(
    object = population$GetSexStructure(),
    expected = "explicit_two_sex"
  )

  population$SetSexStructure("sex_ratio_at_age")

  #' @description Test that sex_ratio_at_age round-trips.
  expect_equal(
    object = population$GetSexStructure(),
    expected = "sex_ratio_at_age"
  )

  clear()
})

## Edge handling ----
# No Edge handling for now.

## Error handling ----
test_that("SetSexStructure rejects unknown and unimplemented values", {
  population <- methods::new(Population)

  #' @description Test that unknown sex_structure names error.
  expect_error(
    object = population$SetSexStructure("unknown"),
    regexp = "unknown sex_structure"
  )

  #' @description Test that implicit_two_sex is rejected until implemented.
  expect_error(
    object = population$SetSexStructure("implicit_two_sex"),
    regexp = "unknown sex_structure"
  )

  clear()
})
