// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "population/population.hpp"
#include "../../tests/gtest/test_population_test_fixture.hpp"

namespace {

// CatchAtAge_CalculateMortality
// IO correctness
TEST_F(CAAPrepareTestFixture,
       HandlesCorrectInput_CatchAtAge_CalculateMortality) {
  this->InitializeCAA();
  catch_at_age_model->Prepare();
  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);

  for (int year = 0; year < population->n_years; year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;
      // Call FIMS CalculateMortality() to compare FIMS mortality
      // values with expected values later.
      catch_at_age_model->CalculateMortality(population, i_age_year, year, age);
    }
  }

  std::vector<double> mortality_F(population->n_ages * population->n_years,
                                  0.0);
  std::vector<double> mortality_Z(population->n_ages * population->n_years,
                                  0.0);
  for (int year = 0; year < population->n_years; year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;

      for (int fleet_index = 0; fleet_index < population->n_fleets;
           fleet_index++) {
        mortality_F[i_age_year] +=
            population->fleets[fleet_index]->Fmort[year] *
            population->fleets[fleet_index]->selectivity->evaluate(
                population->ages[age]);
      }
      EXPECT_LT(abs(dq["mortality_F"][i_age_year] - mortality_F[i_age_year]),
                1e-7);

      mortality_Z[i_age_year] = fims_math::exp(population->log_M[i_age_year]) +
                                dq["mortality_F"][i_age_year];
      EXPECT_LT(abs(dq["mortality_Z"][i_age_year] - mortality_Z[i_age_year]),
                1e-7);
    }
  }
}

TEST_F(CAAPrepareTestFixture,
       ExplicitTwoSexCalculateMortalityFillsFAndZByPartition) {
  catch_at_age_model->populations[0]->sex_structure =
      fims_popdy::SexStructure::kExplicitTwoSex;
  this->InitializeCAA();
  catch_at_age_model->Prepare();
  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);
  const size_t n_strata = fims_popdy::MakeDefaultSexPartitionSpec().n_strata();
  const size_t pooled_size =
      static_cast<size_t>(population->n_years * population->n_ages);

  for (int year = 0; year < population->n_years; year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;
      catch_at_age_model->CalculateMortality(population, i_age_year, year,
                                             age);
    }
  }

  for (int year = 0; year < population->n_years; year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;
      const double f_pooled = dq["mortality_F"][i_age_year];
      for (size_t stratum = 0; stratum < n_strata; stratum++) {
        const size_t i_stratum_age_year = stratum * pooled_size + i_age_year;
        EXPECT_DOUBLE_EQ(dq["mortality_F_by_partition"][i_stratum_age_year],
                         f_pooled);
        EXPECT_DOUBLE_EQ(
            dq["mortality_Z_by_partition"][i_stratum_age_year],
            dq["mortality_M_by_partition"][i_stratum_age_year] + f_pooled);
      }
    }
  }
}

TEST_F(CAAPrepareTestFixture,
       ExplicitTwoSexSexSpecificSelectivityYieldsSexSpecificF) {
  catch_at_age_model->populations[0]->sex_structure =
      fims_popdy::SexStructure::kExplicitTwoSex;
  this->InitializeCAA();

  auto female_sel = std::make_shared<fims_popdy::LogisticSelectivity<double>>();
  female_sel->inflection_point.resize(1);
  female_sel->inflection_point[0] = 5.0;
  female_sel->slope.resize(1);
  female_sel->slope[0] = 0.5;

  auto male_sel = std::make_shared<fims_popdy::LogisticSelectivity<double>>();
  male_sel->inflection_point.resize(1);
  male_sel->inflection_point[0] = 10.0;
  male_sel->slope.resize(1);
  male_sel->slope[0] = 0.5;

  for (size_t fleet_ = 0; fleet_ < population->n_fleets; fleet_++) {
    population->fleets[fleet_]->selectivity = female_sel;
    population->fleets[fleet_]->selectivity_by_partition = {female_sel,
                                                            male_sel};
  }

  catch_at_age_model->Prepare();
  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);
  const size_t pooled_size =
      static_cast<size_t>(population->n_years * population->n_ages);

  bool found_sex_difference = false;
  for (int year = 0; year < population->n_years; year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;
      catch_at_age_model->CalculateMortality(population, i_age_year, year,
                                             age);

      const size_t i_female = i_age_year;
      const size_t i_male = pooled_size + i_age_year;
      const double f_female = dq["mortality_F_by_partition"][i_female];
      const double f_male = dq["mortality_F_by_partition"][i_male];

      EXPECT_DOUBLE_EQ(dq["mortality_F"][i_age_year], f_female);
      EXPECT_DOUBLE_EQ(dq["mortality_Z_by_partition"][i_female],
                       dq["mortality_M_by_partition"][i_female] + f_female);
      EXPECT_DOUBLE_EQ(dq["mortality_Z_by_partition"][i_male],
                       dq["mortality_M_by_partition"][i_male] + f_male);
      if (std::abs(f_female - f_male) > 1e-8) {
        found_sex_difference = true;
      }
    }
  }
  EXPECT_TRUE(found_sex_difference);
}

// CatchAtAge_CalculateInitialNumbersAA
// IO correctness
TEST_F(CAAEvaluateTestFixture,
       HandlesCorrectInput_CatchAtAge_CalculateInitialNumbersAA) {
  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);

  std::vector<double> numbers_at_age(n_years * n_ages, 0);

  for (int year = 0; year < population->n_years; year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;

      catch_at_age_model->CalculateInitialNumbersAA(population, i_age_year,
                                                    age);

      numbers_at_age[i_age_year] =
          fims_math::exp(population->log_init_naa[age]);
      EXPECT_EQ(dq["numbers_at_age"][i_age_year], numbers_at_age[i_age_year]);
    }
  }
}

// CatchAtAge_CalculateUnfishedNumbersAA and
// CatchAtAge_CalculateUnfishedSpawningBiomass
// IO correctness
TEST_F(
    CAAEvaluateTestFixture,
    HandlesCorrectInput_CatchAtAge_CalculateUnfishedNumbersAA_CalculateUnfishedSpawningBiomass) {
  std::vector<double> test_unfished_numbers_at_age((n_years + 1) * n_ages, 0);
  std::vector<double> test_unfished_spawning_biomass(n_years + 1, 0);

  size_t pop_id = population->GetId();
  auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(pop_id);

  for (int year = 0; year < (population->n_years + 1); year++) {
    for (int age = 0; age < population->n_ages; age++) {
      int i_age_year = year * population->n_ages + age;

      if (age == 0) {
        dq["unfished_numbers_at_age"][i_age_year] =
            fims_math::exp(population->recruitment->log_rzero[0]);
        test_unfished_numbers_at_age[i_age_year] =
            fims_math::exp(population->recruitment->log_rzero[0]);
      }

      if (year == 0 && age > 0) {
        catch_at_age_model->CalculateUnfishedNumbersAA(population, i_age_year,
                                                       age - 1, age);
        test_unfished_numbers_at_age[i_age_year] =
            test_unfished_numbers_at_age[i_age_year - 1] *
            fims_math::exp(-fims_math::exp(population->log_M[i_age_year - 1]));
      }

      if (year > 0 && age > 0) {
        int i_agem1_yearm1 = (year - 1) * population->n_ages + (age - 1);
        EXPECT_GT(population->M[i_agem1_yearm1], 0.0);
        catch_at_age_model->CalculateUnfishedNumbersAA(population, i_age_year,
                                                       i_agem1_yearm1, age);
        test_unfished_numbers_at_age[i_age_year] =
            test_unfished_numbers_at_age[i_agem1_yearm1] *
            fims_math::exp(-fims_math::exp(population->log_M[i_agem1_yearm1]));
      }

      if (age == (population->n_ages - 1)) {
        int i_agem1_yearm1 = 0;
        if (year == 0) {
          i_agem1_yearm1 = age - 1;
        } else {
          i_agem1_yearm1 = (year - 1) * population->n_ages + (age - 1);
        }
        test_unfished_numbers_at_age[i_age_year] +=
            test_unfished_numbers_at_age[i_agem1_yearm1 + 1] *
            fims_math::exp(
                -fims_math::exp(population->log_M[i_agem1_yearm1 + 1]));
      }

      catch_at_age_model->CalculateMaturityAA(population, i_age_year, age);
      catch_at_age_model->CalculateUnfishedSpawningBiomass(
          population, i_age_year, year, age);

      test_unfished_spawning_biomass[year] +=
          dq["proportion_mature_at_age"][i_age_year] *
          population->proportion_female[age] *
          test_unfished_numbers_at_age[i_age_year] *
          population->growth->evaluate(year, population->ages[age]);

      EXPECT_EQ(dq["unfished_numbers_at_age"][i_age_year],
                test_unfished_numbers_at_age[i_age_year]);
      EXPECT_GT(dq["unfished_numbers_at_age"][i_age_year], 0.0);
    }

    EXPECT_NEAR(dq["unfished_spawning_biomass"][year],
                test_unfished_spawning_biomass[year], 1e-7);
    EXPECT_GT(dq["unfished_spawning_biomass"][year], 0.0);
  }
}
}  // namespace
