// Instructions ----
// This file follows the format generated by FIMS:::use_gtest_template().
// Necessary tests include input and output (IO) correctness [IO
// correctness], edge-case handling [Edge handling], and built-in errors and
// warnings [Error handling]. See `?FIMS:::use_gtest_template` for more
// information. Every test should have a description comment.
// More assertion macros provided by GoogleTest can be found at
// https://google.github.io/googletest/reference/assertions.html.

#include "gtest/gtest.h"
#include "../../tests/gtest/test_population_test_fixture.hpp"

namespace
{

    // Population_InitializePrepare
    // IO correctness
    TEST_F(CAAInitializeTestFixture, HandlesCorrectInput_InputData)
    { 
        this->InitializeCAA();
        EXPECT_EQ(catch_at_age_model->populations[0]->id_g, id_g);
        EXPECT_EQ(catch_at_age_model->populations[0]->n_years, n_years);
        EXPECT_EQ(catch_at_age_model->populations[0]->n_ages, n_ages);
        EXPECT_EQ(catch_at_age_model->populations[0]->fleets.size(), n_fleets);
        EXPECT_EQ(catch_at_age_model->populations[0]->n_fleets, n_fleets);
    }

    TEST_F(CAAInitializeTestFixture, HandlesCorrectInput_Population_InitializeCAA)
    {
        this->InitializeCAA();
        auto& dq = catch_at_age_model->GetPopulationDerivedQuantities(0);
        EXPECT_EQ(dq["mortality_F"].size(), n_years * n_ages);
        EXPECT_EQ(dq["mortality_Z"].size(), n_years * n_ages);
        EXPECT_EQ(dq["proportion_mature_at_age"].size(), (n_years+1) * n_ages);
       // EXPECT_EQ(dq["weight_at_age"].size(), n_ages);
        EXPECT_EQ(dq["unfished_numbers_at_age"].size(), (n_years + 1) * n_ages);
        EXPECT_EQ(dq["numbers_at_age"].size(), (n_years + 1) * n_ages);
        EXPECT_EQ(dq["total_catch_weight"].size(), n_years);
        EXPECT_EQ(dq["total_catch_numbers"].size(), n_years);
        EXPECT_EQ(dq["biomass"].size(), (n_years + 1));
        EXPECT_EQ(dq["unfished_biomass"].size(), (n_years + 1));
        EXPECT_EQ(dq["unfished_spawning_biomass"].size(), (n_years + 1));
        EXPECT_EQ(dq["spawning_biomass"].size(), n_years + 1);
        EXPECT_EQ(catch_at_age_model->populations[0]->proportion_female.size(), n_ages);
        EXPECT_EQ(catch_at_age_model->populations[0]->M.size(), n_years * n_ages);
        EXPECT_EQ(dq["expected_recruitment"].size(), n_years + 1);
        EXPECT_EQ(dq["sum_selectivity"].size(), n_years * n_ages);
        // Model 1 (default sex_structure) does not allocate partitioned
        // life-history DQs.
        EXPECT_EQ(dq.find("numbers_at_age_by_partition"), dq.end());
        EXPECT_EQ(dq.find("mortality_M_by_partition"), dq.end());
        EXPECT_EQ(dq.find("mortality_F_by_partition"), dq.end());
        EXPECT_EQ(dq.find("mortality_Z_by_partition"), dq.end());
        EXPECT_EQ(dq.find("proportion_female_at_age_year"), dq.end());
    }

    TEST_F(CAAInitializeTestFixture,
           ExplicitTwoSexRegistersPopulationPartitionedLifeHistoryDQs)
    {
        population->sex_structure = fims_popdy::SexStructure::kExplicitTwoSex;
        this->InitializeCAA();
        auto &dq = catch_at_age_model->GetPopulationDerivedQuantities(0);
        const size_t n_strata =
            fims_popdy::MakeDefaultSexPartitionSpec().n_strata();

        EXPECT_EQ(dq["numbers_at_age_by_partition"].size(),
                  n_strata * (n_years + 1) * n_ages);
        EXPECT_EQ(dq["mortality_M_by_partition"].size(),
                  n_strata * n_years * n_ages);
        EXPECT_EQ(dq["mortality_F_by_partition"].size(),
                  n_strata * n_years * n_ages);
        EXPECT_EQ(dq["mortality_Z_by_partition"].size(),
                  n_strata * n_years * n_ages);
        EXPECT_EQ(dq["proportion_female_at_age_year"].size(),
                  n_ages * n_years);
    }

    TEST_F(CAAPrepareTestFixture, HandlesCorrectInput_Population_InitializeCAA_Prepare)
    {
        this->InitializeCAA();
        catch_at_age_model->Prepare();
        auto &dq = catch_at_age_model->GetPopulationDerivedQuantities(1);

        // vector size type = n_years and vector value = 0
        EXPECT_EQ(dq["total_catch_weight"],
            fims::Vector<double>(n_years, 0)
        );
        EXPECT_EQ(dq["total_catch_numbers"],
            fims::Vector<double>(n_years, 0)
        );
        EXPECT_EQ(dq["mortality_F"],
            fims::Vector<double>(n_years * n_ages, 0)
        );
        EXPECT_EQ(dq["mortality_Z"],
            fims::Vector<double>(n_years * n_ages, 0)
        );
        EXPECT_EQ(dq["numbers_at_age"],
            fims::Vector<double>((n_years + 1) * n_ages, 0)
        );
        EXPECT_EQ(dq["unfished_numbers_at_age"],
            fims::Vector<double>((n_years + 1) * n_ages, 0)
        );
        EXPECT_EQ(dq["biomass"],
            fims::Vector<double>(n_years + 1, 0) 
        );
        EXPECT_EQ(dq["spawning_biomass"],
            fims::Vector<double>(n_years + 1, 0) 
        );
        EXPECT_EQ(dq["unfished_biomass"],
            fims::Vector<double>(n_years + 1, 0) 
        );
        EXPECT_EQ(dq["unfished_spawning_biomass"],
            fims::Vector<double>(n_years + 1, 0) 
        );
        EXPECT_EQ(dq["proportion_mature_at_age"],
            fims::Vector<double>((n_years + 1) * n_ages, 0) 
        );
        EXPECT_EQ(dq["expected_recruitment"],
            fims::Vector<double>(n_years + 1, 0) 
        );
        EXPECT_EQ(dq["sum_selectivity"],
            fims::Vector<double>(n_years * n_ages, 0) 
        );
        
      

        // Test population.M
        fims::Vector<double> M(n_years * n_ages, 0);
        for (int i = 0; i < n_years * n_ages; i++)
        {
            M[i] = fims_math::exp(catch_at_age_model->populations[0]->log_M[i]);
            EXPECT_EQ(catch_at_age_model->populations[0]->M[i], M[i]);
        }
        EXPECT_EQ(catch_at_age_model->populations[0]->M.size(), n_years * n_ages);

        // proportion_female is user-provided; Prepare() does not reset it
        fims::Vector<double> p_female(n_ages, 0.5);
        for(int i = 0; i < n_ages; i++)
        {
            EXPECT_EQ(catch_at_age_model->populations[0]->proportion_female[i], p_female[i]);
        }
        
    }

    TEST_F(CAAPrepareTestFixture,
           ExplicitTwoSexPooledLogMDuplicatesToPartitionedMortalityM) {
        catch_at_age_model->populations[0]->sex_structure =
            fims_popdy::SexStructure::kExplicitTwoSex;
        this->InitializeCAA();
        catch_at_age_model->Prepare();

        auto &population = catch_at_age_model->populations[0];
        auto &dq = catch_at_age_model->GetPopulationDerivedQuantities(1);
        const size_t n_strata =
            fims_popdy::MakeDefaultSexPartitionSpec().n_strata();

        for (size_t age = 0; age < static_cast<size_t>(n_ages); age++) {
            for (size_t year = 0; year < static_cast<size_t>(n_years); year++) {
                const size_t i_age_year = age * n_years + year;
                const double expected_m = fims_math::exp(population->log_M[i_age_year]);
                for (size_t stratum = 0; stratum < n_strata; stratum++) {
                    const size_t i_stratum_age_year =
                        stratum * (n_years * n_ages) + i_age_year;
                    EXPECT_EQ(dq["mortality_M_by_partition"][i_stratum_age_year],
                              expected_m);
                }
            }
        }
    }

    TEST_F(CAAPrepareTestFixture,
           ExplicitTwoSexPartitionedLogMFillsMortalityMByPartition) {
        catch_at_age_model->populations[0]->sex_structure =
            fims_popdy::SexStructure::kExplicitTwoSex;
        this->InitializeCAA();
        auto &population = catch_at_age_model->populations[0];
        const size_t n_strata =
            fims_popdy::MakeDefaultSexPartitionSpec().n_strata();
        const size_t pooled_size = static_cast<size_t>(n_years * n_ages);
        population->log_M.resize(n_strata * pooled_size);
        for (size_t stratum = 0; stratum < n_strata; stratum++) {
            for (size_t i = 0; i < pooled_size; i++) {
                population->log_M[stratum * pooled_size + i] =
                    fims_math::log(static_cast<double>(0.2 + 0.1 * stratum));
            }
        }

        catch_at_age_model->Prepare();
        auto &dq = catch_at_age_model->GetPopulationDerivedQuantities(1);
        const double female_m = fims_math::exp(fims_math::log(0.2));
        const double male_m = fims_math::exp(fims_math::log(0.3));
        const double pooled_m = (female_m + male_m) / 2.0;
        for (size_t i = 0; i < pooled_size; i++) {
            EXPECT_DOUBLE_EQ(dq["mortality_M_by_partition"][i], female_m);
            EXPECT_DOUBLE_EQ(dq["mortality_M_by_partition"][pooled_size + i],
                             male_m);
            EXPECT_DOUBLE_EQ(population->M[i], pooled_m);
        }
    }
} // namespace

